### PR TITLE
add context processors

### LINKED ISSUE #4: Add an option for including the request into the template context, similar to what Pyramid does.
As per title, this would be a handy feature.

### PR DESCRIPTION
**Pull request by IlyaSemenov**
This adds context processors, backported from aiohttp-jinja2 with some optimizations. Tests included. Fixes #4.

### CODE REVIEW

**Comment by IlyaSemenov** [comment]
Okey-dokey, boss, let me add a test for that.

**Comment by asvetlov** [comment]
Please fix line length

**Comment by asvetlov** [comment]
Thanks

**Comment by asvetlov** [comment]
aiohttp_mako 0.2.0 released

**Pull request merged**
